
export const schoolData = [

    {
        label: "sclname",
        className: "browser-default",
        name: "schoolName",
        id: "schoolName",
        input: "[object Object]",
        type: "select",
        tabIndex: 0,
        options: [
            { value: "", label: "Select school name" },
            { value: 253, label: "-" },
            { value: 163, label: "A bayan p2" },
            { value: 241, label: "ACS Doha International School" },
            { value: 165, label: "Al Hammad International School" },
            { value: 166, label: "Al Hammad International School" },
            { value: 9, label: "Al Hekma International School" },
            { value: 10, label: "Al Hekma International School (Al Maamoura)" },
            { value: 11, label: "Al Jazeera Academy" },
            { value: 12, label: "Al Maha English Private ( Girls )" },
            { value: 13, label: "Al Maha English Private School ( Male )" },
            { value: 312, label: "Al Rayyan private school" },
            { value: 14, label: "Al Wataniya International School" },
            { value: 15, label: "Al-Khor International School (British Stream)" },
            { value: 16, label: "Al-Khor International School (Indian Stream)" },
            { value: 247, label: "alsashbal" },
            { value: 111, label: "Alwakrah" },
            { value: 17, label: "American School of doha" },
            { value: 303, label: "Applab" },
            { value: 19, label: "Aspire Academy for Sports Excellence" },
          
            { value: 66, label: "Qatar Academy ( Al-Khur branch)" },
            { value: 67, label: "Qatar Academy ( al-wajba )" },
            { value: 68, label: "Qatar Academy (Al-Wakra)" },
            { value: 333, label: 'Others' },
        ],
    },
    {
        name: "schoolNameOther",
        placeholder: "scother",
        id: "schoolNameOther",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        label: "sclname",
        refValue: "333",
        refId: "schoolName"
    },
    {

        name: "schoolPhoneNumber",
        placeholder: "tysclno",
        id: "schoolPhoneNumber",
        className: "",
        type: "number",
        autoComplete: "no",
        defaultValue: "",
        label: "sclmb",
        refValue: "333",
        refId: "schoolName"
    },
    {
        name: "schoolEmail",
        placeholder: "sclmail",
        id: "schoolEmail",
        placeholder: "tysclmail",
        className: "",
        type: "email",
        autoComplete: "no",
        defaultValue: "",
        label: "School Email",
        refValue: "333",
        refId: "schoolName"
    },
    {
        name: "repName",
        placeholder: "typerep",
        id: "repName",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        label: "repscl",
    },
    {
        name: "repNameArabic",
        placeholder: "repar",
        id: "repNameArabic",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        label: "nar",

    },
    {
        name: "qid",
        placeholder: "typegid",
        id: "qid",
        className: "",
        type: "text",
        maxLength: 11,
        autoComplete: "no",
        defaultValue: "",
        label: "qid",

    },
    {
        name: "repPosition",
        placeholder: "typos",
        id: "repPosition",
        className: "",
        type: "text",
        autoComplete: "no",
        label: "pos",
        defaultValue: "",
    },

    {
        name: "repMobile",
        placeholder: "pgmob",
        className: "",
        id: "repMobile",
        maxLength: 8,
        label: "phone",
        type: "number",
        autoComplete: "no",
        defaultValue: "",

    },
    {
        name: "repEmail",
        placeholder: "pgmail",
        id: "repEmail",
        className: "fontEnglish",
        type: "email",
        autoComplete: "no",
        defaultValue: "",

    },
    {
        name: "agree",
        switchkey: "checkbox",
        id: "agree",
        type: "checkbox",
        label: "term",
        ariaLabel: "Read terms and condition",
        className: "modal-trigger underline-text",

    },

]


