export const Studentdata = [
    {
        name: "name",
        placeholder: "Type student name in English",
        id: "name",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        htmlFor: "name",
        className: "asterisk",
        label: "Student name in English ",
        schoolKey: "333"

    },
    {
        label: "Student name in Arabic",
        name: "nameArabic",
        placeholder: "Type student name in Arabic",
        id: "nameArabic",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        htmlFor: "nameArabic",
        schoolKey: "333"

    },
    {
        label: "Date of Birth",
        arialabel: "choose date of birth button",
        type: "date",
        className: "example-custom-input",
        ariahidden: "true",
        htmlFor: "dob",
        schoolKey: "333"
    },
    {
        label: "Nationality ",
        type: "select",
        className: "browser-default",
        name: "nationality",
        id: "nationality",
        tabIndex: 0,
        options: [

            { value: '1', label: 'Afghanistan' },
            { value: '2', label: 'Albania' },
            { value: '3', label: 'Algeria' },
            { value: '4', label: 'American Samoa' },
            { value: '5', label: 'Andorra' },
            { value: '6', label: 'Angola' },
            { value: '189', label: 'Anguilla' },
            { value: '3', label: 'Antarctica' },
            { value: '8', label: 'Antigua and Barbuda' },
            { value: '10', label: 'Argentina' },
            { value: '16', label: 'Armenia' },
            { value: '152', label: 'Aruba' },
            { value: '11', label: 'Australia' },
            { value: '12', label: 'Austria' },
            { value: '9', label: 'Azerbaijan' },
            { value: '13', label: 'Bahamas' },
            { value: '14', label: 'Bahrain' },
            { value: '15', label: 'Bangladesh' },
            { value: '17', label: 'Barbados' },
            { value: '34', label: 'Belarus' },
            { value: '18', label: 'Belgium' },
            { value: '26', label: 'Belize' },
            { value: '59', label: 'Benin' },
            { value: '19', label: 'Bermuda' },
            { value: '20', label: 'Bhutan' },
            { value: '21', label: 'Bolivia, Plurinational State of' },
            { value: '22', label: 'Bosnia and Herzegovina' },
            { value: '23', label: 'Botswana' },
            { value: '25', label: 'Brazil' },
            { value: '30', label: 'Brunei Darussalam' },
            { value: '31', label: 'Bulgaria' },
            { value: '241', label: 'Burkina Faso' },
            { value: '33', label: 'Burundi' },
            { value: '35', label: 'Cambodia' },
            { value: '36', label: 'Cameroon' },
            { value: '37', label: 'Canada' },
            { value: '38', label: 'Cape Verde' },
            { value: '40', label: 'Central African Republic' },
            { value: '42', label: 'Chad' },
            { value: '43', label: 'Chile' },
            { value: '44', label: 'China' },
            { value: '48', label: 'Colombia' },
            { value: '49', label: 'Comoros' },
            { value: '51', label: 'Congo' },
            { value: '52', label: 'Congo, the Democratic Republic of the' },
            { value: '53', label: 'Cook Islands' },
            { value: '54', label: 'Costa Rica' },
            { value: '55', label: 'Croatia' },
            { value: '56', label: 'Cuba' },
            { value: '57', label: 'Cyprus' },
            { value: '58', label: 'Czech Republic' },
            { value: '109', label: 'Côte d\'Ivoire' },
            { value: '60', label: 'Denmark' },
            { value: '79', label: 'Djibouti' },
            { value: '61', label: 'Dominica' },
            { value: '62', label: 'Dominican Republic' },
            { value: '63', label: 'Ecuador' },
            { value: '233', label: 'Egypt' },
            { value: '64', label: 'El Salvador' },
            { value: '65', label: 'Equatorial Guinea' },
            { value: '67', label: 'Eritrea' },
            { value: '68', label: 'Estonia' },
            { value: '66', label: 'Ethiopia' },
            { value: '69', label: 'Faroe Islands' },
            { value: '72', label: 'Fiji' },
            { value: '73', label: 'Finland' },
            { value: '75', label: 'France' },
            { value: '76', label: 'French Guiana' },
            { value: '77', label: 'French Polynesia' },
            { value: '80', label: 'Gabon' },
            { value: '82', label: 'Gambia' },
            { value: '81', label: 'Georgia' },
            { value: '84', label: 'Germany' },
            { value: '85', label: 'Ghana' },
            { value: '86', label: 'Gibraltar' },
            { value: '88', label: 'Greece' },
            { value: '89', label: 'Greenland' },
            { value: '90', label: 'Grenada' },
            { value: '91', label: 'Guadeloupe' },
            { value: '92', label: 'Guam' },
            { value: '93', label: 'Guatemala' },
            { value: '94', label: 'Guinea' },
            { value: '178', label: 'Guinea-Bissau' },
            { value: '95', label: 'Guyana' },
            { value: '96', label: 'Haiti' },
            { value: '98', label: 'Holy See (Vatican City State)' },
            { value: '99', label: 'Honduras' },
            { value: '100', label: 'Hong Kong' },
            { value: '101', label: 'Hungary' },
            { value: '102', label: 'Iceland' },
            { value: '103', label: 'India' },
            { value: '104', label: 'Indonesia' },
            { value: '105', label: 'Iran, Islamic Republic of' },
            { value: '106', label: 'Iraq' },
            { value: '107', label: 'Ireland' },
            { value: '108', label: 'Italy' },
            { value: '110', label: 'Jamaica' },
            { value: '111', label: 'Japan' },
            { value: '113', label: 'Jordan' },
            { value: '112', label: 'Kazakhstan' },
            { value: '114', label: 'Kenya' },
            { value: '87', label: 'Kiribati' },
            { value: '115', label: 'Korea, Democratic Peoples Republic' }
        ],
        schoolKey: "333"
    },
    {
        label: "School Name ",
        name: "schoolName",
        id: "schoolName",
        type: "select",
        options: [
            { value: "", label: "Select school name" },
            { value: '0', label: 'Other' },
        ],
        schoolKey: "333"
    },
    ,
    {
        name: "qid",
        placeholder: "Type your QID",
        id: "qid",
        className: "",
        maxLength: 11,
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        htmlFor: "qid",
        label: "QID",
        schoolKey: "333"
    },
    {
        type: "radio",
        label: "Gender",
        htmlFor: "gender",
        id: "gender",
        details: [{
            className: "Male",
            ariachecked: "false",
            id: "Male",
            arialabelledby: "gender Male",
            type: "radio",
            labelid: "_Male",
            label: "Male",
            htmlFor: "Male",
            schoolKey: "333"
        },
        {
            className: "Female",
            ariachecked: "false",
            id: "Female",
            arialabelledby: "gender Female",
            type: "radio",
            labelid: "_Female",
            label: "Female",
            htmlFor: "Female",
            schoolKey: "333"
        }]
    },
    {
        name: "grade",
        type: "select",
        id: "grade",
        label: "Grade",
        htmlFor: "grade",
        defaultSelectText: "Select your grade",
        options: [
            { text: "Select your grade" },
            { text: "Grade 1" },
            { text: "Grade 2" },
            { text: "Grade 3" },
            { text: "Grade 4" },
            { text: "Grade 5" },
            { text: "Grade 6" },
            { text: "Grade 7" },
            { text: "Grade 8" },
            { text: "Grade 9" },
            { text: "Grade 10" },
            { text: "Grade 11" },
            { text: "Grade 12" }
        ],
        schoolKey: "333"
    },
    {
        name: "email",
        type: "text",
        placeholder: "Type your email",
        id: "email",
        className: "fontEnglish",
        type: "email",
        defaultValue: "",
        label: "Email",
        schoolKey: "333"
    },
    {
        name: "mobile",
        type: "mobile",
        placeholder: "Type your mobile number",
        id: "mobile",
        className: "",
        type: "number",
        defaultValue: "",
        label: "Mobile Number",
        ariaLabel: "Mobile number starting with country code +974",
        maxLength: 8,
        htmlFor: "mobile",
        schoolKey: "333"
    },
    {
        name: "parentQid",
        placeholder: "Type guardian QID",
        id: "parentQid",
        className: "",
        maxLength: 11,
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        htmlFor: "parentQid",
        label: "Guardian QID",
        schoolKey: "333"
    },
    {
        name: "parentName",
        placeholder: "Type your guardian name",
        id: "parentparentNameQid",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        htmlFor: "parentName",
        label: "Guardian Name",
        schoolKey: "333"
    },
    {
        name: "relation",
        type: "select",
        id: "relation",
        label: "Relation",
        htmlFor: "relation",
        defaultSelectText: "Select relation",
        options: [
            { text: "Select relation" },
            { text: "Father" },
            { text: "Mother" },
            { text: "Sister" },
            { text: "Brother" },
            { text: "Grandmother" },
            { text: "Grandfather" },
            { text: "Guardian" }
        ],
        schoolKey: "333"
    },
    {
        name: "parentMobile",
        type: "mobile",
        placeholder: "Type guardian mobile number",
        id: "parentMobile",
        className: "",
        type: "number",
        defaultValue: "",
        label: "Guardian Mobile 1",
        ariaLabel: "Mobile number starting with country code +974",
        maxLength: 8,
        htmlFor: "parentMobile",
        schoolKey: "333"
    },
    {
        name: "parentMobile2",
        type: "mobile",
        placeholder: "Type guardian mobile number 2",
        id: "parentMobile2",
        className: "",
        type: "number",
        defaultValue: "",
        label: "Guardian Mobile 2",
        ariaLabel: "Mobile number starting with country code +974",
        maxLength: 8,
        htmlFor: "parentMobile2",
        schoolKey: "333"
    },
    {
        name: "parentEmail",
        type: "text",
        placeholder: "Type guardian email address",
        id: "parentEmail",
        className: "fontEnglish",
        type: "email",
        defaultValue: "",
        label: "Guardian Email Address",
        schoolKey: "333"
    },
    {
        name: "agree",
        type: "checkbox",
        id: "agree",
        type: "checkbox",
        label: "I agree to the studio 5",
        ariaLabel: "Read terms and condition",
        className: "modal-trigger underline-text",
        schoolKey: "333"
    },

]
