export const Student = [
    {
        name: "name",
        placeholder: "Type student name in English",
        id: "name",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",

    },
    {
        name: "nameArabic",
        placeholder: "Type student name in Arabic",
        id: "nameArabic",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",

    },
    {
        type: "select",
        className: "browser-default",
        name: "nationality",
        id: "nationality",
        tabIndex: 0,
        options: [
            { value: '1', label: 'Afghanistan' },
            { value: '2', label: 'Albania' },
            { value: '3', label: 'Algeria' },
            { value: '4', label: 'American Samoa' },
            { value: '5', label: 'Andorra' },
            { value: '6', label: 'Angola' },
            { value: '7', label: 'Anguilla' },
            { value: '8', label: 'Antarctica' },
            { value: '9', label: 'Antigua and Barbuda' },
            { value: '10', label: 'Argentina' },
            { value: '11', label: 'Armenia' },
            { value: '12', label: 'Aruba' },
            { value: '13', label: 'Australia' },
            { value: '14', label: 'Austria' },
            { value: '15', label: 'Azerbaijan' },
            { value: '16', label: 'Bahamas' },
            { value: '17', label: 'Bahrain' },
            { value: '18', label: 'Bangladesh' },
            { value: '19', label: 'Barbados' },
            { value: '20', label: 'Belarus' },
            { value: '21', label: 'Belgium' },
            { value: '22', label: 'Belize' },
            { value: '23', label: 'Benin' },
            { value: '24', label: 'Bermuda' },
            { value: '25', label: 'Bhutan' },
            { value: '26', label: 'Bolivia, Plurinational State of' },
            { value: '27', label: 'Bosnia and Herzegovina' },
            { value: '28', label: 'Botswana' },
            { value: '29', label: 'Brazil' },
            { value: '30', label: 'Brunei Darussalam' },
            { value: '31', label: 'Bulgaria' },
            { value: '32', label: 'Botswana' },
            { value: '33', label: 'Brazil' },
            { value: '34', label: 'Brunei Darussalam' },
            { value: '35', label: 'Bulgaria' },
            { value: '36', label: 'Burkina Faso' },
            { value: '37', label: 'Burundi' },
            { value: '38', label: 'Cambodia' },
            { value: '39', label: 'Cameroon' },
            { value: '40', label: 'Canada' },
            { value: '41', label: 'Cape Verde<' },
            { value: '42', label: 'Central African Republic' },
            { value: '43', label: 'Chad' },
            { value: '44', label: 'Chile' },
            { value: '45', label: 'China' },
            { value: '46', label: 'Colombia' },
            { value: '47', label: 'Comoros' },
            { value: '48', label: 'Congo' },
            { value: '49', label: 'Congo, the Democratic Republic of the' },
            { value: '50', label: 'Cook Islands' },

            { value: '51', label: 'Costa Rica' },
            { value: '52', label: 'Croatia' },
            { value: '53', label: 'Cuba' },
            { value: '54', label: 'Cyprus' },
            { value: '55', label: 'Czech Republic' },
            { value: '56', label: 'Côte d Ivoire' },
            { value: '57', label: 'Denmark' },
            { value: '58', label: 'Djibouti' },
            { value: '59', label: 'Dominica' },
            { value: '60', label: 'Dominican Republic' },
            { value: '61', label: 'Ecuador' },
            { value: '62', label: 'Egypt' },
            { value: '63', label: 'El Salvador' },
            { value: '64', label: 'Eritrea' },
            { value: '65', label: 'Estonia' },
            { value: '66', label: 'Ethiopia' },
            { value: '67', label: 'Faroe Islands' },
            { value: '68', label: 'Fiji' },
            { value: '69', label: 'Finland' },
            { value: '70', label: 'France' },
            { value: '71', label: 'French Guiana' },
            { value: '72', label: 'French Polynesia' },
            { value: '73', label: 'Gabon' },
            { value: '74', label: 'Gambia ' },
            { value: '75', label: 'Georgia' },
            { value: '76', label: 'Germany' },
            { value: '77', label: 'Ghana' },
            { value: '78', label: 'Gibraltar' },
            { value: '79', label: 'Greece' },
            { value: '80', label: 'Greenland' },
            { value: '81', label: 'Grenada' },
            { value: '82', label: 'Guadeloupe' },
            { value: '83', label: 'Guam' },
            { value: '84', label: 'Guatemala' },
            { value: '85', label: 'Guinea' },
            { value: '86', label: 'Guinea-Bissau' },
            { value: '87', label: 'Guyana' },
            { value: '88', label: 'Haiti' },
            { value: '89', label: 'Holy See (Vatican City State)' },
            { value: '90', label: 'Honduras' },
            { value: '91', label: 'Hong Kong' },
            { value: '92', label: 'Hungary' },
            { value: '93', label: 'Iceland' },
            { value: '94', label: 'India' },
            { value: '95', label: 'Indonesia' },
            { value: '96', label: 'Iran, Islamic Republic of' },
            { value: '97', label: 'Iraq' },
            { value: '98', label: 'Ireland' },
            { value: '99', label: 'Italy' },
            { value: '100', label: 'Jamaica' },

            { value: '101', label: 'Japan' },
            { value: '102', label: 'Jordan' },
            { value: '103', label: 'Kazakhstan' },
            { value: '104', label: 'Kenya' },
            { value: '105', label: 'Kiribati' },
            { value: '106', label: 'Korea, Democratic Peoples Republic of' },
            { value: '107', label: 'Korea, Republic of' },
            { value: '108', label: 'Kyrgyzstan' },
            { value: '109', label: 'Lao Peoples Democratic Republic' },
            { value: '110', label: 'Argentina' },
            { value: '111', label: 'Armenia' },
            { value: '112', label: 'Aruba' },
            { value: '113', label: 'Australia' },
            { value: '114', label: 'Austria' },
            { value: '115', label: 'Azerbaijan' },
            { value: '116', label: 'Bahamas' },
            { value: '117', label: 'Bahrain' },
            { value: '18', label: 'Bangladesh' },
            { value: '119', label: 'Barbados' },
            { value: '120', label: 'Belarus' },

            { value: '121', label: 'Afghanistan' },
            { value: '122', label: 'Albania' },
            { value: '123', label: 'Algeria' },
            { value: '124', label: 'American Samoa' },
            { value: '125', label: 'Andorra' },
            { value: '126', label: 'Angola' },
            { value: '127', label: 'Anguilla' },
            { value: '128', label: 'Antarctica' },
            { value: '129', label: 'Antigua and Barbuda' },
            { value: '130', label: 'Argentina' },
            { value: '131', label: 'Armenia' },
            { value: '132', label: 'Aruba' },
            { value: '133', label: 'Australia' },
            { value: '134', label: 'Austria' },
            { value: '135', label: 'Azerbaijan' },
            { value: '136', label: 'Bahamas' },
            { value: '137', label: 'Bahrain' },
            { value: '138', label: 'Bangladesh' },
            { value: '139', label: 'Barbados' },
            { value: '140', label: 'Belarus' },

            { value: '141', label: 'Afghanistan' },
            { value: '142', label: 'Albania' },
            { value: '143', label: 'Algeria' },
            { value: '144', label: 'American Samoa' },
            { value: '145', label: 'Andorra' },
            { value: '146', label: 'Angola' },
            { value: '147', label: 'Anguilla' },
            { value: '148', label: 'Antarctica' },
            { value: '149', label: 'Antigua and Barbuda' },
            { value: '150', label: 'Argentina' },
            { value: '151', label: 'Armenia' },
            { value: '152', label: 'Aruba' },
            { value: '153', label: 'Australia' },
            { value: '154', label: 'Austria' },
            { value: '155', label: 'Azerbaijan' },
            { value: '156', label: 'Bahamas' },
            { value: '157', label: 'Bahrain' },
            { value: '158', label: 'Bangladesh' },
            { value: '159', label: 'Barbados' },
            { value: '160', label: 'Belarus' },

            { value: '171', label: 'Afghanistan' },
            { value: '172', label: 'Albania' },
            { value: '173', label: 'Algeria' },
            { value: '174', label: 'American Samoa' },
            { value: '175', label: 'Andorra' },
            { value: '176', label: 'Angola' },
            { value: '177', label: 'Anguilla' },
            { value: '178', label: 'Antarctica' },
            { value: '179', label: 'Antigua and Barbuda' },
            { value: '180', label: 'Argentina' },
            { value: '181', label: 'Armenia' },
            { value: '182', label: 'Aruba' },
            { value: '183', label: 'Australia' },
            { value: '184', label: 'Austria' },
            { value: '185', label: 'Azerbaijan' },
            { value: '186', label: 'Bahamas' },
            { value: '187', label: 'Bahrain' },
            { value: '188', label: 'Bangladesh' },
            { value: '189', label: 'Barbados' },
            { value: '190', label: 'Belarus' },

            { value: '191', label: 'Afghanistan' },
            { value: '192', label: 'Albania' },
            { value: '193', label: 'Algeria' },
            { value: '194', label: 'American Samoa' },
            { value: '195', label: 'Andorra' },
            { value: '196', label: 'Angola' },
            { value: '197', label: 'Anguilla' },
            { value: '198', label: 'Antarctica' },
            { value: '199', label: 'Antigua and Barbuda' },
            { value: '200', label: 'Argentina' },
            { value: '201', label: 'Armenia' },
            { value: '202', label: 'Aruba' },
            { value: '203', label: 'Australia' },
            { value: '204', label: 'Austria' },
            { value: '205', label: 'Azerbaijan' },
            { value: '206', label: 'Bahamas' },
            { value: '207', label: 'Bahrain' },
            { value: '208', label: 'Bangladesh' },
            { value: '209', label: 'Barbados' },
            { value: '210', label: 'Belarus' },

            { value: '211', label: 'Armenia' },
            { value: '212', label: 'Aruba' },
            { value: '213', label: 'Australia' },
            { value: '214', label: 'Austria' },
            { value: '215', label: 'Azerbaijan' },
            { value: '216', label: 'Bahamas' },
            { value: '217', label: 'Bahrain' },
            { value: '218', label: 'Bangladesh' },
            { value: '219', label: 'Barbados' },
            { value: '220', label: 'Belarus' },
            { value: '221', label: 'Armenia' },
            { value: '222', label: 'Aruba' },
            { value: '223', label: 'Australia' },
            { value: '224', label: 'Austria' },
            { value: '225', label: 'Azerbaijan' },
            { value: '226', label: 'Bahamas' },
            { value: '227', label: 'Bahrain' },
            { value: '228', label: 'Bangladesh' },
            { value: '229', label: 'Barbados' },
            { value: '230', label: 'Belarus' },





        ],
    },
    {
        name: "schoolName",
        id: "schoolName",
        options: [
            { value: "", label: "Select school name" },
            { value: '0', label: 'Other' },
        ]
    },
    ,
    {
        name: "qid",
        placeholder: "Type your QID",
        id: "qid",
        className: "",
        maxLength: 11,
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        htmlFor: "qid",
        label: "QID",
    },
    {
        type: "radio",
        label: "Gender",
        htmlFor: "gender",
        id: "gender",
        details: [{
            className: "Male",
            ariachecked: "false",
            id: "Male",
            arialabelledby: "gender Male",
            type: "radio",
            labelid: "_Male",
            label: "Male",
            htmlFor: "Male",
        },
        {
            className: "Female",
            ariachecked: "false",
            id: "Female",
            arialabelledby: "gender Female",
            type: "radio",
            labelid: "_Female",
            label: "Female",
            htmlFor: "Female"
        }]
    },
    {
        name: "grade",
        type: "select",
        id: "grade",
        label: "Grade",
        htmlFor: "grade",
        defaultSelectText: "Select your grade",
        options: [
            { text: "Grade 1" },
            { text: "Grade 2" },
            { text: "Grade 3" },
            { text: "Grade 4" },
            { text: "Grade 5" },
            { text: "Grade 6" },
            { text: "Grade 7" },
            { text: "Grade 8" },
            { text: "Grade 9" },
            { text: "Grade 10" },
            { text: "Grade 11" },
            { text: "Grade 12" }
        ]
    },
    {
        name: "email",
        type: "text",
        placeholder: "Type your email",
        id: "email",
        className: "fontEnglish",
        type: "email",
        defaultValue: "",
        label: "Email"
    },
    {
        name: "mobile",
        type: "mobile",
        placeholder: "Type your mobile number",
        id: "mobile",
        className: "",
        type: "text",
        defaultValue: "",
        label: "Mobile Number",
        ariaLabel: "Mobile number starting with country code +974",
        maxLength: 8,
        htmlFor: "mobile",
    },
    {
        name: "parentQid",
        placeholder: "Type guardian QID",
        id: "parentQid",
        className: "",
        maxLength: 11,
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        htmlFor: "parentQid",
        label: "Guardian QID",
    },
    {
        name: "parentName",
        placeholder: "Type your guardian name",
        id: "parentparentNameQid",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",
        htmlFor: "parentName",
        label: "Guardian Name",
    },
    {
        name: "relation",
        type: "select",
        id: "relation",
        label: "Relation",
        htmlFor: "relation",
        defaultSelectText: "Select relation",
        options: [
            { text: "Father" },
            { text: "Mother" },
            { text: "Sister" },
            { text: "Brother" },
            { text: "Grandmother" },
            { text: "Grandfather" },
            { text: "Guardian" }
        ]
    },
    {
        name: "parentMobile",
        type: "mobile",
        placeholder: "Type guardian mobile number",
        id: "parentMobile",
        className: "",
        type: "text",
        defaultValue: "",
        label: "Guardian Mobile 1",
        ariaLabel: "Mobile number starting with country code +974",
        maxLength: 8,
        htmlFor: "parentMobile",
    },
    {
        name: "parentMobile2",
        type: "mobile",
        placeholder: "Type guardian mobile number 2",
        id: "parentMobile2",
        className: "",
        type: "text",
        defaultValue: "",
        label: "Guardian Mobile 2",
        ariaLabel: "Mobile number starting with country code +974",
        maxLength: 8,
        htmlFor: "parentMobile2",
    },
    {
        name: "parentEmail",
        type: "text",
        placeholder: "Type guardian email address",
        id: "parentEmail",
        className: "fontEnglish",
        type: "email",
        defaultValue: "",
        label: "Guardian Email Address"
    },
    {
        name: "agree",
        type: "checkbox",
        id: "agree",
        type: "checkbox",
        label: "I agree to the studio 5",
        ariaLabel: "Read terms and condition",
        className: "modal-trigger underline-text"
    },
    {
        name: "agree",
        type: "checkbox",
        id: "agree",
        type: "checkbox",
        label: "I agree to the studio 5",
        ariaLabel: "Read terms and condition",
        className: "modal-trigger underline-text"
    }
]
{
    Student.map((item) => (
        <div>

        </div>
    ))
}