export const volunteer = [
    {
        name: "name",
        placeholder: "Type name in English",
        id: "name",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",
    },
    {
        name: "nameArabic",
        placeholder: "Type name in Arabic",
        id: "nameArabic",
        className: "",
        type: "text",
        autoComplete: "no",
        defaultValue: "",
    },
    {
        name: "qid",
        placeholder: "Type your QID",
        id: "qid",
        className: "",
        maxLength: 11,
        type: "text",
        autoComplete: "no",
        defaultValue: "",
    },
    {
        type: "radio",
        label: "Gender",
        htmlFor: "gender",
        id: "gender",
        details: [{
            className: "Male",
            ariachecked: "false",
            id: "Male",
            arialabelledby: "gender Male",
            type: "radio",
            labelid: "_Male",
            label: "Male",
            htmlFor: "Male",
        },
        {
            className: "Female",
            ariachecked: "false",
            id: "Female",
            arialabelledby: "gender Female",
            type: "radio",
            labelid: "_Female",
            label: "Female",
            htmlFor: "Female"
        }]
    },
    {
        name: "email",
        placeholder: "Type your email",
        id: "email",
        className: "fontEnglish",
        type: "email",
        autoComplete: "no",
        defaultValue: "",
    },
    {
        name: "mobile_country_code",
        placeholder: "+974",
        id: "mobile_country_code",
        type: "text",
        className: "",
        minLength: 3,
        maxLength: 3,
        disabled: "",
    },
    {
        name: "mobile",
        placeholder: "Type your mobile number",
        id: "mobile",
        className: "",
        maxLength: 8,
        type: "text",
        arialabel: "Mobile number starting with country code +974",
        autoComplete: "no",
        defaultValue: "",
    },
    {
        name: "agree",
        switchkey: "checkbox",
        id: "agree",
        type: "checkbox",
        label: "I agree to the studio 5",
        ariaLabel: "Read terms and condition",
        className: "modal-trigger underline-text"
    }
]